apiVersion: apps/v1
kind: Deployment
metadata:
  name: matrix-antiscam
  labels:
    app: matrix-antiscam
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: matrix-antiscam
  template:
    metadata:
      labels:
        app: matrix-antiscam
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
      - name: matrix-antiscam
        image: {{ .Values.image.repo }}:{{ .Values.image.tag }}
        imagePullPolicy: Always 
        ports:
        - name: http
          containerPort: 7000
        readinessProbe:
          httpGet:
            path: /
            port: 7000
          initialDelaySeconds: 30
          timeoutSeconds: 30
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: config
          mountPath: /app/config
      volumes:
        - name: config
          configMap:
            name: matrix-antiscam-bot-settings
            items:
              - key: privsettings.yaml
                path: privsettings.yaml
              - key: settings.yaml
                path: settings.yaml
