environment: production

port: 8008

domain: web3.foundation

image:
  repo: matrixdotorg/synapse
  tag: v1.2.1

antiscam_image:
   repo: web3f/matrix-antiscam
   tag: latest

db:
  user: synapse_user
  password: password
  name: synapse
  host: postgresql-postgresql

recaptcha:
  publicKey: recaptcha_public
  privateKey: recaptcha_private

macaroonSecretKey: macaroon_secret
formSecret: form_secret

signingKey: signing_key

emailPattern: |-
  .*@web3\.foundation

autojoinRooms:
- "#arrivals:web3.foundation"

antiscam: false

email:
  enabled: false
  smtp_host: "localhost"
  smtp_port: 25
  smtp_user: "user"
  smtp_pass: "password"
  notif_from: "Your Matrix Server"
  riot_base_url: "http://localhost/riot"
