environments:
  production:
  ci:

repositories:
  - name: w3f
    url: https://w3f.github.io/helm-charts

releases:
- name: postgresql
  chart: w3f/postgresql
  version: 3.17.0
  values:
  - ./config/postgresql-values.yaml.gotmpl
