{{ if ne .Values.environment "ci" }}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: riot-web
  namespace: default
spec:
  secretName: riot-web-tls
  issuerRef:
    name: letsencrypt
  dnsNames:
  - riot.{{ .Values.domain }}
  acme:
    config:
    - dns01:
        provider: prod-dns
      domains:
      - riot.{{ .Values.domain }}
{{ end }}
