apiVersion: v1
kind: ConfigMap
metadata:
  name: riot-web
data:
  config.json: |
    {
      "default_hs_url": "https://matrix.web3.foundation",
      "default_is_url": "https://vector.im",
      "disable_custom_urls": true,
      "disable_guests": true,
      "disable_login_language_selector": false,
      "disable_3pid_login": false,
      "brand": "Web3 Foundation",
      "integrations_ui_url": "https://scalar.vector.im/",
      "integrations_rest_url": "https://scalar.vector.im/api",
      "integrations_jitsi_widget_url": "https://scalar.vector.im/api/widgets/jitsi.html",
      "bug_report_endpoint_url": "https://riot.im/bugreports/submit",
      "features": {
        "feature_groups": "labs",
        "feature_pinning": "labs"
      },
      "default_federate": true,
      "default_theme": "light",
      "roomDirectory": {
        "servers": [
          "web3.foundation",
          "matrix.org"
        ]
      },
      "enable_presence_by_hs_url": {
        "https://matrix.web3.foundation": false
      }
    }
