apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: riot-web
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/limit-rps: "10"
spec:
  tls:
  - hosts:
      - riot.{{ .Values.domain }}
    secretName: riot-web-tls
  rules:
  - host: riot.{{ .Values.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: riot-web
          servicePort: {{ .Values.port }}
