{{ if ne .Values.environment "ci" }}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: matrix-server
  namespace: default
spec:
  secretName: matrix-server-tls
  issuerRef:
    name: letsencrypt
  dnsNames:
  - matrix.{{ .Values.domain }}
  acme:
    config:
    - dns01:
        provider: prod-dns
      domains:
      - matrix.{{ .Values.domain }}
{{ end }}
