{{ if ne .Values.environment "ci" }}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: matrix-server
  namespace: default
spec:
  secretName: matrix-server-tls
  issuerRef:
    name: letsencrypt
  dnsNames:
  - matrix.{{ .Values.domain }}
{{ end }}
