apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: matrix-server
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/limit-rps: "10"
spec:
  tls:
  - hosts:
      - matrix.{{ .Values.domain }}
    secretName: matrix-server-tls
  rules:
  - host: matrix.{{ .Values.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: matrix-server
          servicePort: {{ .Values.port }}
