apiVersion: v1
kind: Service
metadata:
  name: matrix-server
  labels:
    app: matrix-server
spec:
  ports:
  - name: http
    port: {{ .Values.port }}
  - name: metrics
    port: 9000
  selector:
    app: matrix-server
